export const FETCH_GEO_LOCATIONS_REQUEST_NAME = 'FETCH_GEO_LOCATIONS';
export const WEATHER_REQUEST_NAME = 'WEATHER_REQUEST_NAME';

export const GPT3_MESSAGE_REQUEST_NAME = 'GPT3_MESSAGE_REQUEST_NAME';
